export interface EventosErrors {
    titulo: string[]
    descripcion?: string[]
    fecha_comienzo: string[]
    fecha_final: string[]
    horas_extras: string[]
    costo_horas_extras: string[]
    costo_horas: string[]
    costo_paquete: string[]
    costo_fecha: string[]
    discount: string[]
    costo_pagado: string[]
    paquete: string[]
    cliente: string[]
    fecha: string[]
    tipo_pago: string[]
    estado_evento: string[]
    quinta: string[]
    hora_extra: string[]
    hora_extras: string[]
}
